django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from csapi import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('csapi.urls')),
    path('user/', include('login.urls')),
    path('', views.index, name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/csapi/urls.py
from django.urls import path
from . import views

app_name = 'csapi'

urlpatterns = [
    path('', views.index),
    path('upload/', views.upload, name='upload'),
    path('origin-images/<int:image_id>/', views.origin_image_show, name='origin_image_show'),
]

django/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

django/csapi/models.py
from django.db import models
from django.contrib.auth.models import User

class OriginImage(models.Model):
    auth_user = models.ForeignKey(User, on_delete=models.CASCADE)
    origin_image = models.ImageField(upload_to = 'origin_images/')

class SeparatedImage(models.Model):
    origin_image = models.ForeignKey(OriginImage, on_delete=models.CASCADE)
    separated_image = models.ImageField(upload_to = 'separated_images/')

django/login/models.py
from django.db import models

# Create your models here.

django/csapi/forms.py
from django import forms
from .models import OriginImage

class UploadForm(forms.ModelForm):
    class Meta:
        model = OriginImage
        fields = {'origin_image'}

django/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email") # add email field

django/csapi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import OriginImage
from .models import SeparatedImage
from .forms import UploadForm
from .tasks import startAPI
import celery

# login required
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'csapi/main.html')

@login_required(login_url='login:login')
def upload(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)

        if form.is_valid():
            origin_image = form.save(commit=False)
            origin_image.auth_user = request.user
            origin_image.save()
            origin_image_id = origin_image.id
            return redirect('csapi:origin_image_show', origin_image_id)
    else:
        form = UploadForm()
    return render(request, 'csapi/upload.html', {
        'form' : form
    })

def origin_image_show(request, image_id):
    origin_image = OriginImage.objects.get(id=image_id)
    try:
        separated_image = SeparatedImage.objects.get(origin_image_id=image_id)
    except SeparatedImage.DoesNotExist:
        separated_image = None
        task_id = startAPI.delay(origin_image.origin_image.url, image_id)
    return render(request, 'csapi/image_show.html', {
        'origin_image' : origin_image,
        'separated_image' : separated_image,
    })

django/login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from login.forms import UserForm

def index(request):
    return HttpResponse('login 페이지입니다')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')

            # user authentication
            user = authenticate(username=username, password=password1)

            # login
            login(request, user)
            return redirect('/api/')
    else:
        form = UserForm()
    return render(request, 'login/signup.html', {'form' : form})

django/templates/csapi/image_show.html
{% block content %}
    <h2>Uploaded Image</h2>
    <h4>{{ origin_image.origin_image.name }}</h4>
    <img src="{{ origin_image.origin_image.url }}"/>
    {% if separated_image %}
        <h5>separated_image {{ separated_image }}</h5>
        <img src="{{ separated_image.separated_image.url }}"/>
    {% else %}
        <h5>image is not here!</h5>
    {% endif %}
{% endblock %}

django/templates/csapi/main.html
{% block content %}
<html>
    <head>
    </head>
    <body>
        {% if user.is_authenticated %}
            <a href="{% url 'login:logout' %}">{{ user.username }} (Logout)</a>
        {% else %}
            <a href="{% url 'login:login' %}">Sign In</a>
            <a href="{% url 'login:signup' %}">Sign Up</a>
        {% endif %}
    </body>
</html>
{% endblock %}

django/templates/csapi/upload.html
{% block content %}
    <h2>Upload Image</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Upload Image</button>
    </form>
{% endblock %}

django/templates/login/login.html
{% block content %}
<html>
    <head>
    </head>
    <body>
        <form method="post" action="{% url 'login:login' %}">
            {% csrf_token %}
                <!-- URL if login success -->
                <input type="hidden" name="next" value="{{ next }}">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}  <!-- field error -->
                        <strong>{{ field.label }}</strong>
                        {{ error }}
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}   <!-- None field error -->
                    <strong>{{ error }}</strong>
                {% endfor %}
            {% endif %}
            <br>
            <label for="username">사용자ID</label>
                <input type="text" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
            <label for="password">비밀번호</label>
                <input type="password" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
            <button type="submit">로그인</button>
        </form>
    </body>
</html>
{% endblock %}

django/templates/login/signup.html
{% block content %}
<html>
    <head>
    </head>

    <body>
        <h1>회원가입 페이지</h1><br>
        <div>
            <form method="post" action="{% url 'login:signup' %}">
                {% csrf_token %}

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}  <!-- field error -->
                            <strong>{{ field.label }}</strong>
                            {{ error }}
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}   <!-- None field error -->
                        <strong>{{ error }}</strong>
                    {% endfor %}
                {% endif %}

                <h4>이름 : </h4>
                <input type="text" name="username" value="{{ form.username.value|default_if_none:'' }}">
                <h4>비밀번호 : </h4>
                <input type="password" name="password1" value="{{ form.password1.value|default_if_none:'' }}">
                <h4>비밀번호 확인 : </h4>
                <input type="password" name="password2" value="{{ form.password2.value|default_if_none:'' }}">
                <h4>이메일 : </h4>
                <input type="email" name="email" value="{{ form.email.value|default_if_none:'' }}">

                <button type="submit">제출</button>
            </form>
        </div>
    </body>
</html>

{% endblock %}